import 'package:revelation/l10n/app_localizations.dart';

String localizedBibleBookCode(AppLocalizations localizations, int bookId) {
  switch (bookId) {
    case 1:
      return localizations.book_code_1;
    case 2:
      return localizations.book_code_2;
    case 3:
      return localizations.book_code_3;
    case 4:
      return localizations.book_code_4;
    case 5:
      return localizations.book_code_5;
    case 6:
      return localizations.book_code_6;
    case 7:
      return localizations.book_code_7;
    case 8:
      return localizations.book_code_8;
    case 9:
      return localizations.book_code_9;
    case 10:
      return localizations.book_code_10;
    case 11:
      return localizations.book_code_11;
    case 12:
      return localizations.book_code_12;
    case 13:
      return localizations.book_code_13;
    case 14:
      return localizations.book_code_14;
    case 15:
      return localizations.book_code_15;
    case 16:
      return localizations.book_code_16;
    case 17:
      return localizations.book_code_17;
    case 18:
      return localizations.book_code_18;
    case 19:
      return localizations.book_code_19;
    case 20:
      return localizations.book_code_20;
    case 21:
      return localizations.book_code_21;
    case 22:
      return localizations.book_code_22;
    case 23:
      return localizations.book_code_23;
    case 24:
      return localizations.book_code_24;
    case 25:
      return localizations.book_code_25;
    case 26:
      return localizations.book_code_26;
    case 27:
      return localizations.book_code_27;
    case 28:
      return localizations.book_code_28;
    case 29:
      return localizations.book_code_29;
    case 30:
      return localizations.book_code_30;
    case 31:
      return localizations.book_code_31;
    case 32:
      return localizations.book_code_32;
    case 33:
      return localizations.book_code_33;
    case 34:
      return localizations.book_code_34;
    case 35:
      return localizations.book_code_35;
    case 36:
      return localizations.book_code_36;
    case 37:
      return localizations.book_code_37;
    case 38:
      return localizations.book_code_38;
    case 39:
      return localizations.book_code_39;
    case 40:
      return localizations.book_code_40;
    case 41:
      return localizations.book_code_41;
    case 42:
      return localizations.book_code_42;
    case 43:
      return localizations.book_code_43;
    case 44:
      return localizations.book_code_44;
    case 45:
      return localizations.book_code_45;
    case 46:
      return localizations.book_code_46;
    case 47:
      return localizations.book_code_47;
    case 48:
      return localizations.book_code_48;
    case 49:
      return localizations.book_code_49;
    case 50:
      return localizations.book_code_50;
    case 51:
      return localizations.book_code_51;
    case 52:
      return localizations.book_code_52;
    case 53:
      return localizations.book_code_53;
    case 54:
      return localizations.book_code_54;
    case 55:
      return localizations.book_code_55;
    case 56:
      return localizations.book_code_56;
    case 57:
      return localizations.book_code_57;
    case 58:
      return localizations.book_code_58;
    case 59:
      return localizations.book_code_59;
    case 60:
      return localizations.book_code_60;
    case 61:
      return localizations.book_code_61;
    case 62:
      return localizations.book_code_62;
    case 63:
      return localizations.book_code_63;
    case 64:
      return localizations.book_code_64;
    case 65:
      return localizations.book_code_65;
    case 66:
      return localizations.book_code_66;
    default:
      throw RangeError.value(bookId, 'bookId');
  }
}

String localizedBibleBookName(AppLocalizations localizations, int bookId) {
  switch (bookId) {
    case 1:
      return localizations.book_name_1;
    case 2:
      return localizations.book_name_2;
    case 3:
      return localizations.book_name_3;
    case 4:
      return localizations.book_name_4;
    case 5:
      return localizations.book_name_5;
    case 6:
      return localizations.book_name_6;
    case 7:
      return localizations.book_name_7;
    case 8:
      return localizations.book_name_8;
    case 9:
      return localizations.book_name_9;
    case 10:
      return localizations.book_name_10;
    case 11:
      return localizations.book_name_11;
    case 12:
      return localizations.book_name_12;
    case 13:
      return localizations.book_name_13;
    case 14:
      return localizations.book_name_14;
    case 15:
      return localizations.book_name_15;
    case 16:
      return localizations.book_name_16;
    case 17:
      return localizations.book_name_17;
    case 18:
      return localizations.book_name_18;
    case 19:
      return localizations.book_name_19;
    case 20:
      return localizations.book_name_20;
    case 21:
      return localizations.book_name_21;
    case 22:
      return localizations.book_name_22;
    case 23:
      return localizations.book_name_23;
    case 24:
      return localizations.book_name_24;
    case 25:
      return localizations.book_name_25;
    case 26:
      return localizations.book_name_26;
    case 27:
      return localizations.book_name_27;
    case 28:
      return localizations.book_name_28;
    case 29:
      return localizations.book_name_29;
    case 30:
      return localizations.book_name_30;
    case 31:
      return localizations.book_name_31;
    case 32:
      return localizations.book_name_32;
    case 33:
      return localizations.book_name_33;
    case 34:
      return localizations.book_name_34;
    case 35:
      return localizations.book_name_35;
    case 36:
      return localizations.book_name_36;
    case 37:
      return localizations.book_name_37;
    case 38:
      return localizations.book_name_38;
    case 39:
      return localizations.book_name_39;
    case 40:
      return localizations.book_name_40;
    case 41:
      return localizations.book_name_41;
    case 42:
      return localizations.book_name_42;
    case 43:
      return localizations.book_name_43;
    case 44:
      return localizations.book_name_44;
    case 45:
      return localizations.book_name_45;
    case 46:
      return localizations.book_name_46;
    case 47:
      return localizations.book_name_47;
    case 48:
      return localizations.book_name_48;
    case 49:
      return localizations.book_name_49;
    case 50:
      return localizations.book_name_50;
    case 51:
      return localizations.book_name_51;
    case 52:
      return localizations.book_name_52;
    case 53:
      return localizations.book_name_53;
    case 54:
      return localizations.book_name_54;
    case 55:
      return localizations.book_name_55;
    case 56:
      return localizations.book_name_56;
    case 57:
      return localizations.book_name_57;
    case 58:
      return localizations.book_name_58;
    case 59:
      return localizations.book_name_59;
    case 60:
      return localizations.book_name_60;
    case 61:
      return localizations.book_name_61;
    case 62:
      return localizations.book_name_62;
    case 63:
      return localizations.book_name_63;
    case 64:
      return localizations.book_name_64;
    case 65:
      return localizations.book_name_65;
    case 66:
      return localizations.book_name_66;
    default:
      throw RangeError.value(bookId, 'bookId');
  }
}
