name: revelation-x
title: Revelation
version: '1.0.4.126'
license: Apache-2.0
summary: Revelation Study app.
description: |
  This program has been created to help all Christians, regardless of denomination,
  better understand the Book of Revelation. This task may seem difficult – nearly impossible,
  considering the differences in doctrines, cultures, customs, generations,
  and even Bible translations. In order to overcome all these differences
  accumulated over 2,000 years, let us try to get as close as possible to
  the time when the book was written. To this end, we will begin by reading a text as close as possible to the original.
  As primary sources for the text, we will choose all the papyri and uncials containing
  the text of the Book of Revelation in the original language.
  I believe that God has governed which sources of the Book of Revelation, and to what extent,
  have been preserved to bear witness to His Revelation.
icon: snap/gui/revelation-x.png
type: app

base: core22
grade: stable
confinement: strict

source-code: https://github.com/karnauhov/Revelation
contact: https://t.me/karnauhov
website: https://www.revelation.website
issues: https://github.com/karnauhov/Revelation/issues
donation: https://www.revelation.website/demo/en.html#join

apps:
  revelation-x:
    command: revelation
    extensions: [gnome]
    plugs:
      - home
      - network
      - desktop
      - desktop-legacy
      - jack1
      - shared-memory
      - audio-playback
      - pulseaudio
      - alsa

parts:
  revelation-x:
    source: .
    build-environment:
      - PUB_CACHE: /root/.pub-cache
    plugin: flutter
    flutter-channel: stable
    flutter-target: lib/main.dart
    override-build: |
      set -eux
      apt-get update
      apt-get install -y git unzip xz-utils
      git clone https://github.com/flutter/flutter.git -b stable /usr/local/flutter
      export PATH="$PATH:/usr/local/flutter/bin"
      flutter doctor
      cd $CRAFT_PART_SRC
      rm -rf build
      flutter precache --linux
      flutter clean
      flutter pub get
      flutter build linux --release --dart-define-from-file=api-keys.json --target lib/main.dart
      mkdir -p $CRAFT_PART_INSTALL/
      cp -r build/linux/*/release/bundle/* $CRAFT_PART_INSTALL/
    build-packages:
      - curl
      - libgstreamer1.0-dev
      - libgstreamer-plugins-base1.0-dev
      - libpulse0 
    stage-packages:
      - libgstreamer1.0-0
      - libgstreamer-plugins-base1.0-0

architectures:
  - build-on: [ amd64 ]
  - build-on: [ arm64 ]
